name: Github CI/CD Actions
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: tree
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: node --version
      - name: Installing Packages
        run: npm install
      - name: Building App
        run: npm run build
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          # vercel-args: '--prod' #Optional
        run: echo "Hooray!"
