name: Github CI/CD Actions
on: [push]
jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: tree
            - uses: actions/setup-node@v3
              with:
                node-version: 17